---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=13000
      - PGID=13000
      - TZ=/etc/timezone
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5 #optional
    volumes:
      - /path/to/jellyfin/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=13001
      - PGID=13000
      - TZ=/etc/timezone
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881 # Change this port to a random number between 1024 & 65535, also apply this to the ports below
    volumes:
      - /home/mediauser/config/qbittorrent:/config
      - /mnt/tank/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13002
      - PGID=13000
      - TZ=/etc/timezone
    volumes:
      - /home/mediauser/config/sabnzbd:/config
      - /mnt/tank/usenet/incomplete:/incomplete-downloads
      - /mnt/tank/usenet/complete:/downloads
    ports:
      - 8081:8081
    restart: unless-stopped


sudo useradd sonarr -u 13003
sudo useradd radarr -u 13004
sudo useradd prowlarr -u 13005
sudo useradd configarr -u 13006
sudo useradd bazarr -u 13007
sudo useradd seerr -u 13008
sudo useradd homepage -u 13009
sudo useradd maintainarr -u 13010
sudo useradd unmanic -u 13011
