---
services:
  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent.local
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORT=8080/tcp
    volumes:
      - /home/mediauser/config/qbittorrent:/config
      - /mnt/tank:/torrents
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
    
  sabnzbd:
    image: ghcr.io/hotio/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd.local
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
      - WEBUI_PORTS=8081/tcp
    volumes:
      - /home/mediauser/config/sabnzbd:/config
      - /mnt/tank:/usenet
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8081:8081
    restart: unless-stopped

  sonarr:
    image: ghcr.io/hotio/sonarr:latest
    container_name: sonarr
    hostname: sonarr.local
    environment:
      - PUID=13003
      - PGID=13000
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - /home/mediauser/config/sonarr:/config
      - /mnt/tank:/tv
      - /etc/localtime:/etc/localtime:ro      
    ports:
      - 8989:8989
    restart: unless-stopped
    

sudo useradd prowlarr -u 13005
sudo useradd configarr -u 13006
sudo useradd bazarr -u 13007
sudo useradd seerr -u 13008
sudo useradd homepage -u 13009
sudo useradd maintainarr -u 13010
sudo useradd unmanic -u 13011
